services:
  dex:
    image: ghcr.io/dexidp/dex:v2.43.1-distroless
    command: ["dex", "serve", "/config.yaml"]
    ports:
      - 5556:5556
    configs:
      - source: config.yaml
        target: /config.yaml

  postgres:
    image: 'postgres:17.5-alpine3.20'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: jetski
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'

configs:
  config.yaml:
    content: |
      issuer: http://localhost:5556/dex
      web:
        http: 0.0.0.0:5556
        allowedOrigins: ['*']
      storage:
        type: sqlite3
      staticClients:
        - id: ui
          name: 'Jetski Development'
          public: true
          redirectURIs:
          - 'http://localhost:4200'
          - 'http://localhost:8080'
      enablePasswordDB: true
      staticPasswords:
        - email: "admin@example.com"
          # bcrypt hash of the string "password": $(echo password | htpasswd -BinC 10 admin | cut -d: -f2)
          hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
          username: "admin"
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
      expiry:
        idTokens: "5m"

volumes:
  postgres:
