[tools]
node = "24"
go = "1.24"
golangci-lint = "2"

[env]
JETSKI_ENV = '.env.development.local'

[tasks.tidy]
run = "go mod tidy"

[tasks.lint]
depends = ["tidy"]
run = "golangci-lint run"

[tasks.serve]
run = "go run cmd/main.go serve"
